### ISSUE TITLE
Move To Mouth: getting stuck in error cases

### ISSUE THREAD

**Issue by atharva-kashyap** [personalrobotics/feeding_web_interface#90]
If the robot tries to move to the user's mouth and fails (because it collides with the user's mouth), then user gets stuck (because there is no recourse). Both options (go back/continue) require the arm to not be in collision.

**Comment by amalnanavati** [comment]
[`ada_feeding`#128](https://github.com/personalrobotics/ada_feeding/pull/128) should partially solve this, because the "resume"/"retry" action will be `MoveToMouth` which will disable wheelchair collisions. However, the `Back` option will still be `MoveToStagingConfiguration`, which expects the robot to be out-of-collision. To address this, I should add a `MoveFromMouthToStagingConfiguration` motion that is called when the user clicks "Back" from `MoveToMouth`
